#!/bin/sh

set -eu

nft=/usr/sbin/nft
docker=/usr/bin/docker
ip=/usr/sbin/ip
jq=/usr/bin/jq
set_name=ddev_router_ipv4
chain_name=ddev-router-firewall
network=ddev_default
destination=10.121.16.20
lock=/run/ddev-router-firewall.lock
comment=ddev-router-firewall

fail_closed() {
	ensure_set
	printf 'flush set ip filter %s\n' "$set_name" | "$nft" -f -
}

ensure_set() {
	"$nft" add table ip filter
	"$nft" list set ip filter "$set_name" >/dev/null 2>&1 ||
		"$nft" add set ip filter "$set_name" '{ type ipv4_addr; }'
}

ensure_objects() {
	ensure_set
	"$nft" list chain ip filter "$chain_name" >/dev/null 2>&1 ||
		"$nft" add chain ip filter "$chain_name"
}

router_ip() {
	"$docker" inspect --type container ddev-router 2>/dev/null |
		"$jq" -er '
			.[0]
			| select(.State.Running == true)
			| select(.Name == "/ddev-router")
			| select(.Config.Image == "ddev/ddev-traefik-router:v1.25.4")
			| select(.Config.Labels["com.ddev.platform"] == "ddev")
			| select((.NetworkSettings.Networks | keys) == ["ddev_default"])
			| .NetworkSettings.Networks.ddev_default.IPAddress
			| select(test("^[0-9]{1,3}(\\.[0-9]{1,3}){3}$"))
		'
}

bridge_interface() {
	gateway=$("$docker" network inspect "$network" --format '{{(index .IPAM.Config 0).Gateway}}' 2>/dev/null) || return 1
	"$ip" -o -4 addr show | awk -v gateway="$gateway" \
		'{ split($4, address, "/"); if (address[1] == gateway && $2 ~ /^br-/) { print $2; exit } }'
}

reconcile() {
	ensure_objects
	router=$(router_ip) || return 1
	bridge=$(bridge_interface) || return 1
	[ -n "$bridge" ] || return 1
	printf 'flush chain ip filter %s\nadd rule ip filter %s ip saddr @%s ip daddr %s iifname "%s" tcp dport 4096 counter accept comment "%s"\nadd rule ip filter %s ip saddr @%s ip daddr %s iifname "%s" tcp dport 8082 counter accept comment "%s"\nflush set ip filter %s\nadd element ip filter %s { %s }\n' \
		"$chain_name" "$chain_name" "$set_name" "$destination" "$bridge" "$comment" \
		"$chain_name" "$set_name" "$destination" "$bridge" "$comment" \
		"$set_name" "$set_name" "$router" | "$nft" -f -
}

remove_jumps() {
	"$nft" -a list chain ip filter ufw-after-input 2>/dev/null |
		awk -v comment="$comment" '$0 ~ comment { for (i = 1; i <= NF; i++) if ($i == "handle") print $(i + 1) }' |
		while IFS= read -r handle; do
			"$nft" delete rule ip filter ufw-after-input handle "$handle"
		done
}

install_rules() {
	ensure_objects
	remove_jumps
	"$nft" flush chain ip filter "$chain_name"
	"$nft" add rule ip filter ufw-after-input jump "$chain_name" comment "$comment"
}

exec 9>"$lock"
flock -x 9

case ${1:-reconcile} in
	reconcile)
		if ! reconcile; then
			fail_closed
		fi
		;;
	clear)
		ensure_objects
		fail_closed
		;;
	install-rules)
		install_rules
		if ! reconcile; then
			fail_closed
		fi
		;;
	remove-rules)
		remove_jumps
		"$nft" list chain ip filter "$chain_name" >/dev/null 2>&1 && "$nft" flush chain ip filter "$chain_name"
		ensure_objects
		fail_closed
		;;
	*)
		exit 64
		;;
esac
